Tablayout
SJSU-CS-systems-group/DDD pull request #217
Opened 2024-07-24 23:15 UTC by Innominate-Majesty

what's working;
- tab layout
- page views (main/usb and permissions)
- buttons
- switched buttons to their respective fragment class

what's not working:
- checkmarks / x symbols
- it's not checking for permissions for some reason

2024-07-24 23:16 UTC, Innominate-Majesty commented
oh, please ignore the commented out lines. i need them for reference (in case) and will be deleting it after a code cleanup

2024-07-24 23:47 UTC, breed requested changes

2024-07-24 23:47 UTC, breed commented on BundleClient/app/build.gradle
> -        minSdk 34 // Required at least 34 for JDK 17 -> enable BufferedInputStream transferTo in BundleCore
undo this change so that it doesn't look like you are changing the minSdk

2024-07-24 23:47 UTC, breed commented on build.gradle
> -        agp_version = '8.2.2'
i don't think we want this change either

2024-07-25 00:14 UTC, breed approved these changes

2024-07-25 00:15 UTC, merged