resolved server call crash on bundle transport
SJSU-CS-systems-group/DDD pull request #340
Opened 2024-09-20 21:02 UTC by RonCodes88

2024-09-20 21:24 UTC, ManasC478 approved these changes

2024-09-24 20:36 UTC, breed requested changes

2024-09-24 20:36 UTC, breed commented on BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportActivity.java
> +    public static Context applicationContext;
we don't want to do a static here.

2024-09-24 20:44 UTC, breed commented on BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportToBundleServerManager.java
> +                Toast.makeText(BundleTransportActivity.applicationContext,
you should put the application context in the constructor or pass the error back through connectCompete to the fragment create the toast.

2024-09-26 19:19 UTC, breed approved these changes

2024-09-26 20:34 UTC, merged